file: /sys/kernel/debug/ec/ec0/io

current_config: default
configs:
  default:
    cpu_temp:
      realtime_data: 0x68
      multi_data:
        - 0x6a
        - 0x6b
        - 0x6c
        - 0x6d
        - 0x6e
        - 0x6f
    cpu_fan_speed:
      realtime_data: 0x71
      multi_data:
        - 0x72
        - 0x73
        - 0x74
        - 0x75
        - 0x76
        - 0x77
        - 0x78
    gpu_temp:
      realtime_data: 0x80
      multi_data:
        - 0x82
        - 0x83
        - 0x84
        - 0x85
        - 0x86
        - 0x87
    gpu_fan_speed:
      realtime_data: 0x89
      multi_data:
        - 0x8a
        - 0x8b
        - 0x8c
        - 0x8d
        - 0x8e
        - 0x8f
    cooler_boost: 0x98

    realtime_cpu_fan_rpm:
      address: 0xcc
      length: 2

    realtime_gpu_fan_rpm:
      address: 0xca
      length: 2
    fan_mode: 0xf4
    usb_backlight: 0xf7

    battery_charging_threshold: 0xef
